### ISSUE TITLE
Specify folder to use

### ISSUE THREAD

**Issue by spences10** [bahmutov/now-pipeline#26]
Hi, I'm using the `  - DEBUG=now-pipeline now-pipeline ` script trying to get to grips with this tool

From the output here:

```sh
Mon, 08 Jan 2018 09:19:36 GMT now-pipeline [ 'package.json',
  '.npmignore',
  'README.md',
  'LICENSE',
  'gatsby-config.js',
  'gatsby-browser.js',
  'gatsby-node.js',
  'gatsby-ssr.js',
  '.travis.yml',
  'src/layouts/index.js',
  'src/layouts/components/Button.js',
  ....
```

I'm still not completely clear on what the command `now-pipeline` does, because the output appears to be reading from the root of the project and I want to only deploy the `public` folder in my Gatsby project I'm cd'ing to that folder then running the `now-pipeline` command and getting errors because there's no `package.json` 🤷‍♂️ 

There shouldn't be a `package.json` it's a static site, does that need to be configured as well?

It's not the clearest on how to use, even with the `README.md`

**Comment by spences10** [comment]
Ok, so I thought I could pass the `/public/` folder to `now-pipeline` as I'm presuming that `now-pipeline` is the same as `now` from the terminal on my machine, so I was hoping that I could do that, here's my `.travis.yml`

```yml
sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'

before_script:
  - npm prune

script:
  - npm run build
  # - cd public
  - npm i -g now-pipeline
  - touch .npmignore
  - DEBUG=now-pipeline now-pipeline /public/

  # - now-pipeline --test "npm run deploy"
  # - now-pipeline-list

  # - npm i -g now-pipeline
  # - now-pipeline-prune
  # - now-pipeline 'npm run deploy'
  # - now-pipeline --alias scottspence.now.sh

# after_success:
```

And I have the output for it [here] it seems to be deploying the whole project, well that's what I'm gleaning from **now-pipeline deploying 480 files**:

```sh
4.97s$ DEBUG=now-pipeline now-pipeline /public/
Mon, 08 Jan 2018 10:53:10 GMT now-pipeline deploying 480 files
Mon, 08 Jan 2018 10:53:10 GMT now-pipeline [ 'package.json',
....
```
[here]: https://gist.github.com/anonymous/404f521327055c65abeaf46bef4ec773
